name: inductor-rocm

on:
  pull_request:
    paths:
      # from "ciflow/inductor" in .github/labeler.yml
      - 'torch/_decomp/**'
      - 'torch/_dynamo/**'
      - 'torch/_export/**'
      - 'torch/_inductor/**'
      - 'benchmarks/dynamo/**'
      - 'torch/_subclasses/fake_tensor.py'
      - 'torch/_subclasses/fake_utils.py'
      - 'torch/_subclasses/meta_utils.py'
      - 'test/distributed/test_dynamo_distributed.py'
      - 'test/distributed/test_inductor_collectives.py'
      - 'torch/_functorch/_aot_autograd/**'
      - 'torch/_functorch/aot_autograd.py'
      - 'torch/_functorch/partitioners.py'
      - '.ci/docker/ci_commit_pins/**'
      - '.github/ci_commit_pins/**'
      - 'c10/core/Sym*'
      - 'torch/fx/experimental/symbolic_shapes.py'
      - 'torch/fx/experimental/recording.py'
      - 'torch/fx/experimental/sym_node.py'
      - 'torch/fx/experimental/validator.py'
      - 'torch/fx/experimental/proxy_tensor.py'
      - 'test/distributed/_tensor/test_dtensor_compile.py'
      - 'test/distributed/tensor/parallel/test_fsdp_2d_parallel.py'
      - 'torch/distributed/_tensor/**'
      - 'torch/distributed/fsdp/**'
      - 'torch/csrc/inductor/**'
      - 'test/cpp/aoti_abi_check/**'
      - 'test/cpp/aoti_inference/**'
      # from "module: inductor" in .github/labeler.yml
      - 'test/inductor/**'
  push:
    branches:
      - main
      - release/*
    tags:
      - ciflow/inductor-rocm/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}-${{ github.event.schedule }}
  cancel-in-progress: true

permissions: read-all

jobs:
  get-label-type:
    name: get-label-type
    uses: pytorch/pytorch/.github/workflows/_runner-determinator.yml@main
    if: ${{ (github.event_name != 'schedule' || github.repository == 'pytorch/pytorch') && github.repository_owner == 'pytorch' }}
    with:
      triggering_actor: ${{ github.triggering_actor }}
      issue_owner: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
      curr_branch: ${{ github.head_ref || github.ref_name }}
      curr_ref_type: ${{ github.ref_type }}

  linux-focal-rocm6_2-py3_10-inductor-build:
    name: rocm6.2-py3.10-inductor
    uses: ./.github/workflows/_linux-build.yml
    needs: get-label-type
    with:
      runner_prefix: "${{ needs.get-label-type.outputs.label-type }}"
      build-environment: linux-focal-rocm6.2-py3.10
      docker-image-name: pytorch-linux-focal-rocm-n-py3
      test-matrix: |
        { include: [
          { config: "inductor", shard: 1, num_shards: 2, runner: "linux.rocm.gpu.2" },
          { config: "inductor", shard: 2, num_shards: 2, runner: "linux.rocm.gpu.2" },
        ]}

  linux-focal-rocm6_2-py3_10-inductor-test:
    permissions:
      id-token: write
      contents: read
    name: rocm6.2-py3.10-inductor
    uses: ./.github/workflows/_rocm-test.yml
    needs: linux-focal-rocm6_2-py3_10-inductor-build
    with:
      build-environment: linux-focal-rocm6.2-py3.10
      docker-image: ${{ needs.linux-focal-rocm6_2-py3_10-inductor-build.outputs.docker-image }}
      test-matrix:  ${{ needs.linux-focal-rocm6_2-py3_10-inductor-build.outputs.test-matrix }}
